#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Ph.D. | Sr. Data Scientist  # The title of the book. Will be placed in the left navbar.
author                      : Sophia Yang  # The author of the book
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : name.png  # A path to the book logo